// @generated by Weldr.dev — types file managed. Copy this file before customizing your domain types.

export interface Product {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  description: string;
  price: any;
  inStock: boolean;
}

export interface Order {
  id: string;
  createdAt: string;
  updatedAt: string;
  orderNumber: string;
  status: any;
  totalAmount: any;
  orderDate: string;
}

export type ProductCollection = Product[];
export type ProductInput = Omit<Product, 'id' | 'createdAt' | 'updatedAt'>;
export type ProductUpdate = Partial<ProductInput>;

export type OrderCollection = Order[];
export type OrderInput = Omit<Order, 'id' | 'createdAt' | 'updatedAt'>;
export type OrderUpdate = Partial<OrderInput>;

