// @generated by Weldr.dev — utility module managed. Move helpers into your own utils folder before modifying.
import { type ClassValue, clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}