// @generated by Weldr.dev — navigation file managed. Adjust links via @custom sections or dedicated layout overrides.
export const generatedNavigation = [
  { id: 'menuList', title: 'menuList', path: '/menu-list' }
];
