// @generated by Weldr.dev — drizzle config managed. Regenerate via Weldr.dev or copy before editing migration settings.
import 'dotenv/config';
import { defineConfig } from 'drizzle-kit';

const connectionString = process.env.SUPABASE_DB_URL ?? process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error('Weldr.dev exports require SUPABASE_DB_URL or DATABASE_URL before running drizzle-kit commands.');
}

export default defineConfig({
  schema: './lib/db/schema.ts',
  out: './drizzle',
  dialect: 'postgresql',
  dbCredentials: {
    connectionString,
    ssl: connectionString.includes('supabase.co') ? { rejectUnauthorized: false } : undefined,
  },
});
