// @generated by Weldr.dev — drizzle migration managed. Recreate migrations via Weldr.dev to ensure schema stays in sync.

CREATE TABLE IF NOT EXISTS product (
  "description" TEXT,
  "id" UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  "in_stock" BOOLEAN,
  "name" VARCHAR(255) NOT NULL,
  "price" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS order (
  "id" UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  "order_date" VARCHAR(255) NOT NULL,
  "order_number" VARCHAR(255) NOT NULL UNIQUE,
  "status" VARCHAR(50),
  "total_amount" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS order_product (
  "order_id" UUID NOT NULL,
  "product_id" UUID NOT NULL,
  PRIMARY KEY ("order_id", "product_id"),
  FOREIGN KEY ("order_id") REFERENCES order("id") ON DELETE CASCADE,
  FOREIGN KEY ("product_id") REFERENCES product("id") ON DELETE CASCADE
);
