// @generated by Weldr.dev — route handler managed. Copy API routes to custom files before applying manual changes.
import { NextRequest, NextResponse } from 'next/server';
import { randomUUID } from 'crypto';
import { db } from '@/lib/db/client';
import { order } from '@/lib/db/schema';
import type { Order, OrderInput } from '@/lib/types';

export async function GET() {
  try {
    const records = await db.select().from(order);
    return NextResponse.json(records);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to fetch Order' }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const body: OrderInput = await request.json();
    const record: Order = {
      id: randomUUID(),
      ...(body as OrderInput),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    } as Order;

    const [inserted] = await db.insert(order).values(record).returning();
    return NextResponse.json(inserted ?? record, { status: 201 });
  } catch (error) {
    return NextResponse.json({ error: 'Failed to create Order' }, { status: 500 });
  }
}
