// @generated by Weldr.dev — route handler managed. Copy API routes to custom files before applying manual changes.
import { NextRequest, NextResponse } from 'next/server';
import { eq } from 'drizzle-orm';
import { db } from '@/lib/db/client';
import { order } from '@/lib/db/schema';
import type { Order, OrderInput } from '@/lib/types';

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } },
) {
  try {
    const [record] = await db.select().from(order).where(eq(order.id, params.id));
    if (!record) {
      return NextResponse.json({ error: 'Order not found' }, { status: 404 });
    }
    return NextResponse.json(record);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to fetch Order' }, { status: 500 });
  }
}

export async function PUT(
  request: NextRequest,
  { params }: { params: { id: string } },
) {
  try {
    const body: OrderInput = await request.json();
    const [existing] = await db.select().from(order).where(eq(order.id, params.id));
    if (!existing) {
      return NextResponse.json({ error: 'Order not found' }, { status: 404 });
  }

  const updated: Order = {
    ...(existing as Order),
    ...body,
    id: existing.id,
    updatedAt: new Date().toISOString(),
  } as Order;

  const [saved] = await db.update(order).set(updated).where(eq(order.id, params.id)).returning();
  return NextResponse.json(saved ?? updated);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to update Order' }, { status: 500 });
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: { id: string } },
) {
  try {
    const [existing] = await db.select().from(order).where(eq(order.id, params.id));
    if (!existing) {
      return NextResponse.json({ error: 'Order not found' }, { status: 404 });
    }

    await db.delete(order).where(eq(order.id, params.id)).returning();
    return NextResponse.json({ message: 'Order deleted successfully.' });
  } catch (error) {
    return NextResponse.json({ error: 'Failed to delete Order' }, { status: 500 });
  }
}
