// @generated by Weldr.dev — route handler managed. Copy API routes to custom files before applying manual changes.
import { NextRequest, NextResponse } from 'next/server';
import { randomUUID } from 'crypto';
import { db } from '@/lib/db/client';
import { product } from '@/lib/db/schema';
import type { Product, ProductInput } from '@/lib/types';

export async function GET() {
  try {
    const records = await db.select().from(product);
    return NextResponse.json(records);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to fetch Product' }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const body: ProductInput = await request.json();
    const record: Product = {
      id: randomUUID(),
      ...(body as ProductInput),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    } as Product;

    const [inserted] = await db.insert(product).values(record).returning();
    return NextResponse.json(inserted ?? record, { status: 201 });
  } catch (error) {
    return NextResponse.json({ error: 'Failed to create Product' }, { status: 500 });
  }
}
