// @generated by Weldr.dev — page skeleton managed. Extend behavior inside @custom blocks to retain generator updates.
import React from 'react';

export default function MenuListPage() {
  return (
    <div className="space-y-6">
      <header className="space-y-2">
        <h1 className="text-2xl font-semibold">menuList</h1>
        <p className="text-sm text-muted-foreground">Layout: default</p>
      </header>
      {renderMainRegion()}
    </div>
  );
}

function renderMainRegion() {
  // Layout slot: main (Main)
  // @custom:begin menulist-main
  return (
    <section data-region="main" className="space-y-4">
      <p className="text-sm text-muted-foreground">Extend this @custom block to render additional components.</p>
    </section>
  );
  // @custom:end menulist-main
}
