// @generated by Weldr.dev — layout component managed. Wrap generated pages in @custom regions or copy for bespoke shells.
import type { ReactNode } from 'react';
import { Navigation } from './Navigation';

export function Layout({ children }: { children: ReactNode }) {
  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      <main className="mx-auto w-full max-w-6xl space-y-6 px-6 py-8">
        {children}
      </main>
    </div>
  );
}