'use client';

// @generated by Weldr.dev — navigation component managed. Extend items via @custom regions or wrap in a custom layout component.
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { cn } from '@/lib/utils';
import { Home, Database } from 'lucide-react';
import { generatedNavigation } from '@/app/(generated)/navigation';


export function Navigation() {
  const pathname = usePathname();

  const canonicalLinks = generatedNavigation.map((item) => ({ href: item.path || '/', label: item.title || item.id || 'Page', icon: (item as any).icon }));
  const fallbackLinks = [
    { href: '/', label: 'Home', icon: Home },
    { href: '/product', label: 'Product', icon: Database },
    { href: '/order', label: 'Order', icon: Database },
  ];
  const links = canonicalLinks.length > 0 ? canonicalLinks : fallbackLinks;

  return (
    <nav className="border-b bg-background">
      <div className="container mx-auto flex h-16 items-center justify-between gap-6">
        <div className="font-semibold text-xl">
          App
        </div>
        <div className="flex items-center gap-4">
          {links.map((link) => {
            const Icon = link.icon ?? Database;
            return (
              <Link
                key={link.href}
                href={link.href}
                className={cn(
                  'flex items-center gap-2 text-sm font-medium transition-colors hover:text-primary',
                  pathname === link.href ? 'text-primary' : 'text-muted-foreground',
                )}
              >
                <Icon className="h-4 w-4" />
                <span>{link.label}</span>
              </Link>
            );
          })}
        </div>
      </div>
    </nav>
  );
}
